version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8888:8888"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: salesdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
